### ISSUE TITLE
Import not resolving

### ISSUE THREAD

**Issue by alexstewartja** [mikepenz/LollipopShowcase#12]
I imported the project as a regular Gradle project, as you suggested in an earlier issue. I've synced, re-synced, also invalidated the cache and refreshed the entire project, however the import below doesn't seem to resolve:

<b>import com.mikepenz.lollipopshowcase.R;<b>

Any assistance or explanation would help immensely.

**Comment by mikepenz** [comment]
@alexstewartja seems like you miss something. the above can happen when there is some dependency missing, or an exception in an layout, ... 
You also have the latest build tools, etc?..

**Comment by alexstewartja** [comment]
@mikepenz It seems that I just had to go grab a coffee and come back, because after doing one more Clean and Rebuild of the project, the <b>R.java</b> file was successfully generated by AAPT.

Thanks a lot for the sample project my friend, all the best to you! :+1:
