### ISSUE TITLE
Click on Apk Name to Open in Google Play Store or Add New Panel

### ISSUE THREAD

**Issue by lovebdsobuj** [mikepenz/LollipopShowcase#15]
In details page, How can I implement if user Click on Apk Name to The App Open in Google Play Store.
or 
Bellow App Moments How can I add new panel **Google Play Store Link**?

Sir, Please check the screenshot.
![new panel](https://cloud.githubusercontent.com/assets/10352682/13372077/d23f7700-dd61-11e5-9d29-45f7ebb3be17.png)

click the panel app open in Google Play Store.

**Comment by mikepenz** [comment]
@lovebdsobuj sorry. This is just a small showcase. No development support here.
