### ISSUE TITLE
Please follow Google's Material design guidelines

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mikepenz/LollipopShowcase#8]
look at this link:
http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button
scroll down till you see the text :

"A floating action button shouldn’t float in a random location. Take care when attaching floating action buttons to a toolbar, where it might overlap with or cover other touch targets." .

According to the screenshots of the library, I see that the sample doesn't match the guidelines.
The reason: the floating button is positioned on a place that can easily cover the action items.
It should never be located on the toolbar/actionbar, since there could be items there (plus if you wanted to put there a button, you could simply put an action item instead).

Also, when testing the sample app, and choosing an item, the floating button gets covered by another view, which is also against the guidelines (how would you press the button when it's covered) ...
This is covered on the same page, when you scroll to this text:

"Don’t block floating action buttons with snackbars or toasts."

**Comment by mikepenz** [comment]
@AndroidDeveloperLB 

as far as the current implementation of the LollipopShowcase goes it won't cover any items in the menu, because there are none. But you are right it makes sense to don't use such an FAB if we had an menu item there. 

Can you upload a screenshot when the FAB gets covered by another view? not quite sure what do you mean with it.

**Comment by AndroidDeveloperLB** [comment]
If you use an actionbar/toolbar at the top already, you can just use an action item , and if you want to also use a FAB , you can put it at the bottom.

Here's a screenshot of the current sample, when the FAB is covered by another view :

![device-2015-01-03-183738](https://cloud.githubusercontent.com/assets/5357526/5602962/dc7d4b1e-9377-11e4-9c99-e38ec5c12608.png)

**Comment by mikepenz** [comment]
@AndroidDeveloperLB yeah you are right normally you would place the action item different, but i also tried to show some animation which works pretty cool with the FAB over the toolbar. 

oh i see, totally missed this SnackBar. should move the snackbar to the top :D

**Comment by AndroidDeveloperLB** [comment]
@mikepenz Now that I think about it, they do say to just be careful when attaching the FAB to the app-bar (how many names can the new action bar have, anyway?) .
This means that they are ok with that, but just think it should make sense when doing it. To me it doesn't make sense though.

**Comment by mikepenz** [comment]
@AndroidDeveloperLB it could be an action item that's true, but for this simply purpose and to showcase the new animation framework and to make this button visually more appealing it makes sense. in a real life application you probably wouldn't place it like this. 

if you got another idea how to showcase the animation framework of Android L you can open a pull request. 

thanks for your thoughts on this :)

**Comment by AndroidDeveloperLB** [comment]
ok, here are some cool samples:
http://www.amongtech.com/20-amazing-android-material-design-animations/
https://github.com/ksoichiro/Android-ObservableScrollView
one of the samples even show an FAB on the action bar. I still think it's weird (especially the animation, which is cool though).

**Comment by mikepenz** [comment]
No i think you probably misunderstood me. i know such samples. i implemented the fab to showcase how you implement such an behavior. This showcase is not only to show how the UI could look like, but more how you can implement different functions of the new support / appcompat libraries and the framework itself. It's more a help for devs how they can get started with new functions. 

as written in the description, devs can find how to use following features:
- Toolbar
- RecyclerView
- CardView
- ActionBarDrawerToggle
- Animations (Including animations for the RecyclerView)
- Floating Action Button (FAB)
- RippleDrawables
- Android Compat Theme
- DrawerLayout
- SwipeRefreshLayout

thanks.

**Comment by AndroidDeveloperLB** [comment]
Oh, I see, so you can check the Material design guidelines, and try to show a sample of each.
For example, how to show the chips. I've made a library a long time ago (heavily based on Google's code: https://github.com/AndroidDeveloperLB/ChipsLibrary ) that show chips, but now they have a new design and probably work differently (and better).
BTW, you've put a progress dialog that blocks the user, which is also against the guidelines (and I've caused it to crash by changing orientation and wait).
Other issues I've found:
1. navigation drawer is clickable below the upper item.
2. clicking on items via the second screen put the ripple effect on the middle, no matter where I touch. This is a known issue and was reported on Google Groups. You can handle it by wrapping the rows, I think, with FrameLayout, and add a foreground to it.

**Comment by mikepenz** [comment]
@AndroidDeveloperLB sorry for the late answer. 

1. thanks. i changed it to fix this issue. but there's still anther one lft. 
2. should be fixed now.
3. implemented this one too

**Comment by AndroidDeveloperLB** [comment]
I've also found out that on Kitkat, the action bar's height isn't the normal one that's used on material design.

**Comment by mikepenz** [comment]
@AndroidDeveloperLB yeah i use the system variable for the toolbar height so it's defined by the specific device and android version 

```xml
android:minHeight="?attr/actionBarSize"
```
